version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     - run: |
         docker login -u $DOCKER_USER --password-stdin < $DOCKER_PASS

     # build images
     - run: ./build.sh

     # push images
     - run: ./push.sh